import logging
import json
import re
from datetime import date
from pawpal_system import Task, Pet

# Set up logging for agent actions and guardrails
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")

class PawPalAgent:
    """
    Agentic Workflow Engine for PawPal+.
    Parses natural language requests, plans structured tasks, applies guardrails,
    and returns executable Task objects.
    """
    def __init__(self):
        pass

    def parse_prompt_to_tasks(self, prompt: str, target_pet: Pet) -> list[Task]:
        """
        Parses a natural language instruction into structured PawPal+ Task objects.
        Includes validation guardrails for task times and priorities.
        """
        logging.info(f"[Agent] Processing request for pet '{target_pet.name}': \"{prompt}\"")

        # Mock LLM response parsing (structured output simulation)
        # Parses key actions, times, and priorities from user prompt
        raw_plan = self._simulate_llm_planning(prompt, target_pet.name)
        
        validated_tasks = []
        time_pattern = re.compile(r"^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$")
        valid_priorities = {"low", "medium", "high"}

        for item in raw_plan:
            task_time = item.get("time", "09:00")
            priority = item.get("priority", "medium").lower()

            # --- Guardrail 1: Time Format Check ---
            if not time_pattern.match(task_time):
                logging.warning(f"[Guardrail Flag] Invalid time format '{task_time}' for '{item.get('title')}'. Correcting to '09:00'.")
                task_time = "09:00"

            # --- Guardrail 2: Priority Validation ---
            if priority not in valid_priorities:
                logging.warning(f"[Guardrail Flag] Invalid priority '{priority}'. Defaulting to 'medium'.")
                priority = "medium"

            new_task = Task(
                title=item.get("title", "AI Task"),
                description=item.get("description", "Generated by AI Agent"),
                due_date=date.today(),
                priority=priority,
                status="pending",
                pet=target_pet,
                time=task_time,
                recurrence=item.get("recurrence", "none")
            )

            validated_tasks.append(new_task)
            logging.info(f"[Guardrail Passed] Created task '{new_task.title}' at {new_task.time} [{new_task.priority}]")

        return validated_tasks

    def _simulate_llm_planning(self, prompt: str, pet_name: str) -> list[dict]:
        """Internal helper generating structured plans from prompt keywords."""
        prompt_lower = prompt.lower()
        plan = []

        if "medication" in prompt_lower or "meds" in prompt_lower or "pill" in prompt_lower:
            plan.append({
                "title": f"Give {pet_name} Medication",
                "description": f"Administer prescribed medicine for {pet_name}",
                "time": "08:00",
                "priority": "high",
                "recurrence": "daily"
            })

        if "walk" in prompt_lower or "exercise" in prompt_lower:
            plan.append({
                "title": f"Walk {pet_name}",
                "description": f"Take {pet_name} for daily routine exercise",
                "time": "17:30",
                "priority": "medium",
                "recurrence": "daily"
            })

        if "vet" in prompt_lower or "checkup" in prompt_lower:
            plan.append({
                "title": f"Vet Visit for {pet_name}",
                "description": f"Take {pet_name} to health checkup",
                "time": "11:00",
                "priority": "high",
                "recurrence": "none"
            })

        # Default fallback if prompt is general
        if not plan:
            plan.append({
                "title": f"Care Routine for {pet_name}",
                "description": f"Custom task: {prompt}",
                "time": "10:00",
                "priority": "medium",
                "recurrence": "none"
            })

        return plan